version: '3.8'

services:
  mysql:
    image: mysql:8.1
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_payment_password
      MYSQL_DATABASE: payment
      MYSQL_USER: payment_user
      MYSQL_PASSWORD: payment_password
    ports:
      - "3306:3306"
